version: '3.8'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "127.0.0.1:8888"]
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
