version: '3.8'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8888"]
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - redis

  worker:
    build: .
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with hot-reloading in some environments
    depends_on:
      - web
